import os

from N2G import drawio_diagram

styles_dir = os.environ.get('STYLES')

diagram = drawio_diagram()
diagram.add_diagram("Page-1")
diagram.add_node(id="SMTPSERVER",label="SMTPSERVER",style=styles_dir+"/SMTPSERVER.txt",x_pos="100",y_pos="100",width="60",height="60")
diagram.add_node(id="SYSLOG",label="SYSLOG",style=styles_dir+"/SYSLOG.txt",x_pos="350",y_pos="100",width="60",height="60")
diagram.add_node(id="TAPESERVER",label="TAPESERVER",style=styles_dir+"/TAPESERVER.txt",x_pos="600",y_pos="100",width="60",height="60")
diagram.add_node(id="TAPESERVERLINUX",label="TAPESERVERLINUX",style=styles_dir+"/TAPESERVERLINUX.txt",x_pos="100",y_pos="250",width="60",height="60")
diagram.add_node(id="TAPESERVERWINDOWS",label="TAPESERVERWINDOWS",style=styles_dir+"/TAPESERVERWINDOWS.txt",x_pos="350",y_pos="250",width="60",height="60")
diagram.add_node(id="UNIVERSALDCPSRC",label="UNIVERSALDCPSRC",style=styles_dir+"/UNIVERSALDCPSRC.txt",x_pos="600",y_pos="250",width="60",height="60")
diagram.add_node(id="VBRBACKUPPROXY",label="VBRBACKUPPROXY",style=styles_dir+"/VBRBACKUPPROXY.txt",x_pos="100",y_pos="400",width="60",height="60")
diagram.add_node(id="VBRBACKUPREPOSITORY",label="VBRBACKUPREPOSITORY",style=styles_dir+"/VBRBACKUPREPOSITORY.txt",x_pos="350",y_pos="400",width="60",height="60")
diagram.add_node(id="VBRBACKUPREPOSITORYLINUX",label="VBRBACKUPREPOSITORYLINUX",style=styles_dir+"/VBRBACKUPREPOSITORYLINUX.txt",x_pos="600",y_pos="400",width="60",height="60")
diagram.add_node(id="VBRBACKUPREPOSITORYWINDOWS",label="VBRBACKUPREPOSITORYWINDOWS",style=styles_dir+"/VBRBACKUPREPOSITORYWINDOWS.txt",x_pos="100",y_pos="550",width="60",height="60")
diagram.add_node(id="VBRBACKUPSERVER",label="VBRBACKUPSERVER",style=styles_dir+"/VBRBACKUPSERVER.txt",x_pos="350",y_pos="550",width="60",height="60")
diagram.add_node(id="VBRCDPPROXYDST",label="VBRCDPPROXYDST",style=styles_dir+"/VBRCDPPROXYDST.txt",x_pos="600",y_pos="550",width="60",height="60")
diagram.add_node(id="VBRCDPPROXYSRC",label="VBRCDPPROXYSRC",style=styles_dir+"/VBRCDPPROXYSRC.txt",x_pos="100",y_pos="700",width="60",height="60")
diagram.add_node(id="VBRCONSOLE",label="VBRCONSOLE",style=styles_dir+"/VBRCONSOLE.txt",x_pos="350",y_pos="700",width="60",height="60")
diagram.add_node(id="VBRGIP",label="VBRGIP",style=styles_dir+"/VBRGIP.txt",x_pos="600",y_pos="700",width="60",height="60")
diagram.add_node(id="VBRLOGSHIPPING",label="VBRLOGSHIPPING",style=styles_dir+"/VBRLOGSHIPPING.txt",x_pos="100",y_pos="850",width="60",height="60")
diagram.add_node(id="VBRMOUNTSERVER",label="VBRMOUNTSERVER",style=styles_dir+"/VBRMOUNTSERVER.txt",x_pos="350",y_pos="850",width="60",height="60")
diagram.add_node(id="VBRPOWERNFS",label="VBRPOWERNFS",style=styles_dir+"/VBRPOWERNFS.txt",x_pos="600",y_pos="850",width="60",height="60")
diagram.add_node(id="VBRWANACCELERATOR",label="VBRWANACCELERATOR",style=styles_dir+"/VBRWANACCELERATOR.txt",x_pos="100",y_pos="1000",width="60",height="60")
diagram.add_node(id="VEEAMAI",label="VEEAMAI",style=styles_dir+"/VEEAMAI.txt",x_pos="350",y_pos="1000",width="60",height="60")
diagram.add_node(id="VEEAMUPDATE",label="VEEAMUPDATE",style=styles_dir+"/VEEAMUPDATE.txt",x_pos="600",y_pos="1000",width="60",height="60")
diagram.add_node(id="VEEAMUPDATESIGNATURE",label="VEEAMUPDATESIGNATURE",style=styles_dir+"/VEEAMUPDATESIGNATURE.txt",x_pos="100",y_pos="1150",width="60",height="60")
diagram.add_node(id="VMGUESTOS",label="VMGUESTOS",style=styles_dir+"/VMGUESTOS.txt",x_pos="350",y_pos="1150",width="60",height="60")
diagram.add_node(id="VMGUESTOSLINUX",label="VMGUESTOSLINUX",style=styles_dir+"/VMGUESTOSLINUX.txt",x_pos="600",y_pos="1150",width="60",height="60")
diagram.add_node(id="VMGUESTOSWINDOWS",label="VMGUESTOSWINDOWS",style=styles_dir+"/VMGUESTOSWINDOWS.txt",x_pos="100",y_pos="1300",width="60",height="60")
diagram.add_node(id="VMSQLSERVER",label="VMSQLSERVER",style=styles_dir+"/VMSQLSERVER.txt",x_pos="350",y_pos="1300",width="60",height="60")
diagram.add_node(id="VMWAREESXI",label="VMWAREESXI",style=styles_dir+"/VMWAREESXI.txt",x_pos="600",y_pos="1300",width="60",height="60")
diagram.add_node(id="VMWAREESXICDPDST",label="VMWAREESXICDPDST",style=styles_dir+"/VMWAREESXICDPDST.txt",x_pos="100",y_pos="1450",width="60",height="60")
diagram.add_node(id="VMWAREESXICDPSRC",label="VMWAREESXICDPSRC",style=styles_dir+"/VMWAREESXICDPSRC.txt",x_pos="350",y_pos="1450",width="60",height="60")
diagram.add_node(id="VMWAREVCENTER",label="VMWAREVCENTER",style=styles_dir+"/VMWAREVCENTER.txt",x_pos="600",y_pos="1450",width="60",height="60")
diagram.add_node(id="VMWAREVCENTERCDPDST",label="VMWAREVCENTERCDPDST",style=styles_dir+"/VMWAREVCENTERCDPDST.txt",x_pos="100",y_pos="1600",width="60",height="60")
diagram.add_node(id="VMWAREVCENTERCDPSRC",label="VMWAREVCENTERCDPSRC",style=styles_dir+"/VMWAREVCENTERCDPSRC.txt",x_pos="350",y_pos="1600",width="60",height="60")
diagram.dump_file(filename="portfolio.drawio", folder="./")
