"""
role_mappings.py — Mapping from service name patterns to role identifiers.

All patterns are evaluated in order — last match wins.
"""

ROLE_MAPPINGS = {
    "Backup server": "VBRBACKUPSERVER",
    "XXX%plug-in%": "VBRBACKUPSERVER",
    "Veeam backup & replication console": "VBRCONSOLE",
    "Backup repository": "VBRBACKUPREPOSITORY",
    "XXXBackup repository or gateway server": "VBRBACKUPREPOSITORY",
    "XXXBackup repository or gateway server working with backup repository": "VBRBACKUPREPOSITORY",
    "Source backup repository": "VBRBACKUPREPOSITORYSRC",
    "Target backup repository": "VBRBACKUPREPOSITORYDST",
    "Backup repository (microsoft windows)": "VBRBACKUPREPOSITORYWINDOWS",
    "Backup repository (linux)": "VBRBACKUPREPOSITORYLINUX",       
    "Backup repository (source)": "VBRBACKUPREPOSITORYWANSRC",
    "Backup repository (target)": "VBRBACKUPREPOSITORYWANDST",
    "XXXNFS backup repository%": "NFSREPOSITORY",
    "Mount server": "VBRMOUNTSERVER",
    "Mount server running vPower NFS Service": "VBRPOWERNFS",
    "Backup proxy%": "VBRBACKUPPROXY",
    "Guest interaction proxy": "VBRGIP",
    "Tape Server": "TAPESERVER",
    "Tape server (Linux)": "TAPESERVERLINUX",
    "Tape server (Windows)": "TAPESERVERWINDOWS",
    "Esxi server": "VMWAREESXI",
    "Esxi host": "VMWAREESXI",
    "Vcenter server": "VMWAREVCENTER",
    "Smtp server": "SMTPSERVER",
    "Syslog server": "SYSLOG",
    "Veeam update notification server%": "VEEAMUPDATE",
    "Veeam Update Repository%": "VEEAMUPDATE",
    "%vbr.butler.veeam.com%": "VEEAMUPDATE",
    "Veeam signature update server%": "VEEAMUPDATESIGNATURE",
    "XXXVeeam license update server%": "VEEAMLICENSE",
    "Veeam ai assistant%": "VEEAMAI",
    "WAN accelerator (source)": "VBRWANACCELERATORSRC",
    "WAN accelerator (target)": "VBRWANACCELERATORDST",
    "WAN accelerator (source and target)": "VBRWANACCELERATOR",
    "Backup repository (source)": "VBRBACKUPREPOSITORYWANACCELERATORSRC",
    "Backup repository (target)": "VBRBACKUPREPOSITORYWANACCELERATORDST",
    "MS SQL VM guest OS": "VMSQLSERVER",
    "XXXVM guest OS": "VMGUESTOS",
    "XXXVM guest OS (Microsoft Windows)": "VMGUESTOSWINDOWS",
    "XXXVM guest OS (Linux)": "VMGUESTOSLINUX",
    "XXXVM guest OS (Linux/Unix)": "VMGUESTOSLINUX",
    "Log Shipping server": "VBRLOGSHIPPING",
    "CDP proxy (source)": "VBRCDPPROXYSRC",
    "CDP proxy (target)": "VBRCDPPROXYDST",
    "ESXi CDP (source)": "VMWAREESXICDPSRC",
    "ESXi CDP (target)": "VMWAREESXICDPDST",
    "vCenter Server CDP (source)": "VMWAREVCENTERCDPSRC",
    "vCenter Server CDP (target)": "VMWAREVCENTERCDPDST",   
    "Universal CDP Source": "UNIVERSALDCPSRC",
    "ESXi universal CDP (target)": "VMWAREESXICDPDST",
    "vCenter Server universal CDP (target)": "VMWAREVCENTERCDPDST",   
    "XXXNFS share": "NFSSHARE",
}
