"VBRBACKUPREPOSITORYWINDOWS";"VBRBACKUPREPOSITORY"
"VBRBACKUPREPOSITORYLINUX";"VBRBACKUPREPOSITORY"
"VMWAREESXICDPSRC";"VMWAREESXI"
"VMWAREESXICDPDST";"VMWAREESXI"
"VMWAREVCENTERCDPSRC";"VMWAREVCENTER"
"VMWAREVCENTERCDPDST";"VMWAREVCENTER"
"VMGUESTOSWINDOWS";"VMGUESTOS"
"VMGUESTOSLINUX";"VMGUESTOS"
"VMGUESTOSNIX";"VMGUESTOS"
"VEEAMINFRASTRUCTUREAPPLIANCE";"VBRBACKUPSERVER"
"VBRWANACCELERATORSRC";"VBRWANACCELERATOR"
"VBRWANACCELERATORDST";"VBRWANACCELERATOR"